name: Terraform Build and Deploy
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac --sdk-auth` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
    
    - name: Terraform init
      run: cd .\Part-5\vnet\ && terraform init
    
    - name: Terraform plan
      run: cd .\Part-5\vnet\ && terraform plan
    
    - name: Terraform apply
      run: cd .\Part-5\vnet\ && terraform apply

    
    
